/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnprotectedRouteImport } from './routes/_unprotected'
import { Route as OrganizationalRouteImport } from './routes/_organizational'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnprotectedSignUpRouteImport } from './routes/_unprotected/sign-up'
import { Route as UnprotectedSignInRouteImport } from './routes/_unprotected/sign-in'
import { Route as OrganizationalDashboardRouteImport } from './routes/_organizational/dashboard'
import { Route as AuthenticatedMainRouteImport } from './routes/_authenticated/main'
import { Route as AuthenticatedPreprocessSessionOrgInitRouteImport } from './routes/_authenticated/preprocess/session-org-init'
import { Route as AuthenticatedPreprocessAccountSetupRouteImport } from './routes/_authenticated/preprocess/account-setup'
import { Route as UnprotectedApiElectricPublicOrganizationsRouteImport } from './routes/_unprotected/api/electric/public-organizations'
import { Route as UnprotectedApiDeleteBucketUnprotectedIdRouteImport } from './routes/_unprotected/api/delete-bucket-unprotected.$id'
import { Route as UnprotectedApiAuthSplatRouteImport } from './routes/_unprotected/api/auth.$'
import { Route as OrganizationalApiElectricSelfResourceRolesRouteImport } from './routes/_organizational/api/electric/self-resource-roles'
import { Route as OrganizationalApiElectricSelfOrganizationMembersRouteImport } from './routes/_organizational/api/electric/self-organization-members'
import { Route as AuthenticatedApiElectricSelfOrganizationsRouteImport } from './routes/_authenticated/api/electric/self-organizations'
import { Route as AuthenticatedApiElectricSelfOrganizationMembershipsRouteImport } from './routes/_authenticated/api/electric/self-organization-memberships'

const UnprotectedRoute = UnprotectedRouteImport.update({
  id: '/_unprotected',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationalRoute = OrganizationalRouteImport.update({
  id: '/_organizational',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnprotectedSignUpRoute = UnprotectedSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => UnprotectedRoute,
} as any)
const UnprotectedSignInRoute = UnprotectedSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => UnprotectedRoute,
} as any)
const OrganizationalDashboardRoute = OrganizationalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrganizationalRoute,
} as any)
const AuthenticatedMainRoute = AuthenticatedMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreprocessSessionOrgInitRoute =
  AuthenticatedPreprocessSessionOrgInitRouteImport.update({
    id: '/preprocess/session-org-init',
    path: '/preprocess/session-org-init',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPreprocessAccountSetupRoute =
  AuthenticatedPreprocessAccountSetupRouteImport.update({
    id: '/preprocess/account-setup',
    path: '/preprocess/account-setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const UnprotectedApiElectricPublicOrganizationsRoute =
  UnprotectedApiElectricPublicOrganizationsRouteImport.update({
    id: '/api/electric/public-organizations',
    path: '/api/electric/public-organizations',
    getParentRoute: () => UnprotectedRoute,
  } as any)
const UnprotectedApiDeleteBucketUnprotectedIdRoute =
  UnprotectedApiDeleteBucketUnprotectedIdRouteImport.update({
    id: '/api/delete-bucket-unprotected/$id',
    path: '/api/delete-bucket-unprotected/$id',
    getParentRoute: () => UnprotectedRoute,
  } as any)
const UnprotectedApiAuthSplatRoute = UnprotectedApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => UnprotectedRoute,
} as any)
const OrganizationalApiElectricSelfResourceRolesRoute =
  OrganizationalApiElectricSelfResourceRolesRouteImport.update({
    id: '/api/electric/self-resource-roles',
    path: '/api/electric/self-resource-roles',
    getParentRoute: () => OrganizationalRoute,
  } as any)
const OrganizationalApiElectricSelfOrganizationMembersRoute =
  OrganizationalApiElectricSelfOrganizationMembersRouteImport.update({
    id: '/api/electric/self-organization-members',
    path: '/api/electric/self-organization-members',
    getParentRoute: () => OrganizationalRoute,
  } as any)
const AuthenticatedApiElectricSelfOrganizationsRoute =
  AuthenticatedApiElectricSelfOrganizationsRouteImport.update({
    id: '/api/electric/self-organizations',
    path: '/api/electric/self-organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApiElectricSelfOrganizationMembershipsRoute =
  AuthenticatedApiElectricSelfOrganizationMembershipsRouteImport.update({
    id: '/api/electric/self-organization-memberships',
    path: '/api/electric/self-organization-memberships',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof AuthenticatedMainRoute
  '/dashboard': typeof OrganizationalDashboardRoute
  '/sign-in': typeof UnprotectedSignInRoute
  '/sign-up': typeof UnprotectedSignUpRoute
  '/preprocess/account-setup': typeof AuthenticatedPreprocessAccountSetupRoute
  '/preprocess/session-org-init': typeof AuthenticatedPreprocessSessionOrgInitRoute
  '/api/electric/self-organization-memberships': typeof AuthenticatedApiElectricSelfOrganizationMembershipsRoute
  '/api/electric/self-organizations': typeof AuthenticatedApiElectricSelfOrganizationsRoute
  '/api/electric/self-organization-members': typeof OrganizationalApiElectricSelfOrganizationMembersRoute
  '/api/electric/self-resource-roles': typeof OrganizationalApiElectricSelfResourceRolesRoute
  '/api/auth/$': typeof UnprotectedApiAuthSplatRoute
  '/api/delete-bucket-unprotected/$id': typeof UnprotectedApiDeleteBucketUnprotectedIdRoute
  '/api/electric/public-organizations': typeof UnprotectedApiElectricPublicOrganizationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof AuthenticatedMainRoute
  '/dashboard': typeof OrganizationalDashboardRoute
  '/sign-in': typeof UnprotectedSignInRoute
  '/sign-up': typeof UnprotectedSignUpRoute
  '/preprocess/account-setup': typeof AuthenticatedPreprocessAccountSetupRoute
  '/preprocess/session-org-init': typeof AuthenticatedPreprocessSessionOrgInitRoute
  '/api/electric/self-organization-memberships': typeof AuthenticatedApiElectricSelfOrganizationMembershipsRoute
  '/api/electric/self-organizations': typeof AuthenticatedApiElectricSelfOrganizationsRoute
  '/api/electric/self-organization-members': typeof OrganizationalApiElectricSelfOrganizationMembersRoute
  '/api/electric/self-resource-roles': typeof OrganizationalApiElectricSelfResourceRolesRoute
  '/api/auth/$': typeof UnprotectedApiAuthSplatRoute
  '/api/delete-bucket-unprotected/$id': typeof UnprotectedApiDeleteBucketUnprotectedIdRoute
  '/api/electric/public-organizations': typeof UnprotectedApiElectricPublicOrganizationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_organizational': typeof OrganizationalRouteWithChildren
  '/_unprotected': typeof UnprotectedRouteWithChildren
  '/_authenticated/main': typeof AuthenticatedMainRoute
  '/_organizational/dashboard': typeof OrganizationalDashboardRoute
  '/_unprotected/sign-in': typeof UnprotectedSignInRoute
  '/_unprotected/sign-up': typeof UnprotectedSignUpRoute
  '/_authenticated/preprocess/account-setup': typeof AuthenticatedPreprocessAccountSetupRoute
  '/_authenticated/preprocess/session-org-init': typeof AuthenticatedPreprocessSessionOrgInitRoute
  '/_authenticated/api/electric/self-organization-memberships': typeof AuthenticatedApiElectricSelfOrganizationMembershipsRoute
  '/_authenticated/api/electric/self-organizations': typeof AuthenticatedApiElectricSelfOrganizationsRoute
  '/_organizational/api/electric/self-organization-members': typeof OrganizationalApiElectricSelfOrganizationMembersRoute
  '/_organizational/api/electric/self-resource-roles': typeof OrganizationalApiElectricSelfResourceRolesRoute
  '/_unprotected/api/auth/$': typeof UnprotectedApiAuthSplatRoute
  '/_unprotected/api/delete-bucket-unprotected/$id': typeof UnprotectedApiDeleteBucketUnprotectedIdRoute
  '/_unprotected/api/electric/public-organizations': typeof UnprotectedApiElectricPublicOrganizationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/preprocess/account-setup'
    | '/preprocess/session-org-init'
    | '/api/electric/self-organization-memberships'
    | '/api/electric/self-organizations'
    | '/api/electric/self-organization-members'
    | '/api/electric/self-resource-roles'
    | '/api/auth/$'
    | '/api/delete-bucket-unprotected/$id'
    | '/api/electric/public-organizations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/preprocess/account-setup'
    | '/preprocess/session-org-init'
    | '/api/electric/self-organization-memberships'
    | '/api/electric/self-organizations'
    | '/api/electric/self-organization-members'
    | '/api/electric/self-resource-roles'
    | '/api/auth/$'
    | '/api/delete-bucket-unprotected/$id'
    | '/api/electric/public-organizations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_organizational'
    | '/_unprotected'
    | '/_authenticated/main'
    | '/_organizational/dashboard'
    | '/_unprotected/sign-in'
    | '/_unprotected/sign-up'
    | '/_authenticated/preprocess/account-setup'
    | '/_authenticated/preprocess/session-org-init'
    | '/_authenticated/api/electric/self-organization-memberships'
    | '/_authenticated/api/electric/self-organizations'
    | '/_organizational/api/electric/self-organization-members'
    | '/_organizational/api/electric/self-resource-roles'
    | '/_unprotected/api/auth/$'
    | '/_unprotected/api/delete-bucket-unprotected/$id'
    | '/_unprotected/api/electric/public-organizations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OrganizationalRoute: typeof OrganizationalRouteWithChildren
  UnprotectedRoute: typeof UnprotectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unprotected': {
      id: '/_unprotected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnprotectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organizational': {
      id: '/_organizational'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrganizationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unprotected/sign-up': {
      id: '/_unprotected/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnprotectedSignUpRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/_unprotected/sign-in': {
      id: '/_unprotected/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof UnprotectedSignInRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/_organizational/dashboard': {
      id: '/_organizational/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof OrganizationalDashboardRouteImport
      parentRoute: typeof OrganizationalRoute
    }
    '/_authenticated/main': {
      id: '/_authenticated/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthenticatedMainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preprocess/session-org-init': {
      id: '/_authenticated/preprocess/session-org-init'
      path: '/preprocess/session-org-init'
      fullPath: '/preprocess/session-org-init'
      preLoaderRoute: typeof AuthenticatedPreprocessSessionOrgInitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preprocess/account-setup': {
      id: '/_authenticated/preprocess/account-setup'
      path: '/preprocess/account-setup'
      fullPath: '/preprocess/account-setup'
      preLoaderRoute: typeof AuthenticatedPreprocessAccountSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unprotected/api/electric/public-organizations': {
      id: '/_unprotected/api/electric/public-organizations'
      path: '/api/electric/public-organizations'
      fullPath: '/api/electric/public-organizations'
      preLoaderRoute: typeof UnprotectedApiElectricPublicOrganizationsRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/_unprotected/api/delete-bucket-unprotected/$id': {
      id: '/_unprotected/api/delete-bucket-unprotected/$id'
      path: '/api/delete-bucket-unprotected/$id'
      fullPath: '/api/delete-bucket-unprotected/$id'
      preLoaderRoute: typeof UnprotectedApiDeleteBucketUnprotectedIdRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/_unprotected/api/auth/$': {
      id: '/_unprotected/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof UnprotectedApiAuthSplatRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/_organizational/api/electric/self-resource-roles': {
      id: '/_organizational/api/electric/self-resource-roles'
      path: '/api/electric/self-resource-roles'
      fullPath: '/api/electric/self-resource-roles'
      preLoaderRoute: typeof OrganizationalApiElectricSelfResourceRolesRouteImport
      parentRoute: typeof OrganizationalRoute
    }
    '/_organizational/api/electric/self-organization-members': {
      id: '/_organizational/api/electric/self-organization-members'
      path: '/api/electric/self-organization-members'
      fullPath: '/api/electric/self-organization-members'
      preLoaderRoute: typeof OrganizationalApiElectricSelfOrganizationMembersRouteImport
      parentRoute: typeof OrganizationalRoute
    }
    '/_authenticated/api/electric/self-organizations': {
      id: '/_authenticated/api/electric/self-organizations'
      path: '/api/electric/self-organizations'
      fullPath: '/api/electric/self-organizations'
      preLoaderRoute: typeof AuthenticatedApiElectricSelfOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api/electric/self-organization-memberships': {
      id: '/_authenticated/api/electric/self-organization-memberships'
      path: '/api/electric/self-organization-memberships'
      fullPath: '/api/electric/self-organization-memberships'
      preLoaderRoute: typeof AuthenticatedApiElectricSelfOrganizationMembershipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMainRoute: typeof AuthenticatedMainRoute
  AuthenticatedPreprocessAccountSetupRoute: typeof AuthenticatedPreprocessAccountSetupRoute
  AuthenticatedPreprocessSessionOrgInitRoute: typeof AuthenticatedPreprocessSessionOrgInitRoute
  AuthenticatedApiElectricSelfOrganizationMembershipsRoute: typeof AuthenticatedApiElectricSelfOrganizationMembershipsRoute
  AuthenticatedApiElectricSelfOrganizationsRoute: typeof AuthenticatedApiElectricSelfOrganizationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMainRoute: AuthenticatedMainRoute,
  AuthenticatedPreprocessAccountSetupRoute:
    AuthenticatedPreprocessAccountSetupRoute,
  AuthenticatedPreprocessSessionOrgInitRoute:
    AuthenticatedPreprocessSessionOrgInitRoute,
  AuthenticatedApiElectricSelfOrganizationMembershipsRoute:
    AuthenticatedApiElectricSelfOrganizationMembershipsRoute,
  AuthenticatedApiElectricSelfOrganizationsRoute:
    AuthenticatedApiElectricSelfOrganizationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OrganizationalRouteChildren {
  OrganizationalDashboardRoute: typeof OrganizationalDashboardRoute
  OrganizationalApiElectricSelfOrganizationMembersRoute: typeof OrganizationalApiElectricSelfOrganizationMembersRoute
  OrganizationalApiElectricSelfResourceRolesRoute: typeof OrganizationalApiElectricSelfResourceRolesRoute
}

const OrganizationalRouteChildren: OrganizationalRouteChildren = {
  OrganizationalDashboardRoute: OrganizationalDashboardRoute,
  OrganizationalApiElectricSelfOrganizationMembersRoute:
    OrganizationalApiElectricSelfOrganizationMembersRoute,
  OrganizationalApiElectricSelfResourceRolesRoute:
    OrganizationalApiElectricSelfResourceRolesRoute,
}

const OrganizationalRouteWithChildren = OrganizationalRoute._addFileChildren(
  OrganizationalRouteChildren,
)

interface UnprotectedRouteChildren {
  UnprotectedSignInRoute: typeof UnprotectedSignInRoute
  UnprotectedSignUpRoute: typeof UnprotectedSignUpRoute
  UnprotectedApiAuthSplatRoute: typeof UnprotectedApiAuthSplatRoute
  UnprotectedApiDeleteBucketUnprotectedIdRoute: typeof UnprotectedApiDeleteBucketUnprotectedIdRoute
  UnprotectedApiElectricPublicOrganizationsRoute: typeof UnprotectedApiElectricPublicOrganizationsRoute
}

const UnprotectedRouteChildren: UnprotectedRouteChildren = {
  UnprotectedSignInRoute: UnprotectedSignInRoute,
  UnprotectedSignUpRoute: UnprotectedSignUpRoute,
  UnprotectedApiAuthSplatRoute: UnprotectedApiAuthSplatRoute,
  UnprotectedApiDeleteBucketUnprotectedIdRoute:
    UnprotectedApiDeleteBucketUnprotectedIdRoute,
  UnprotectedApiElectricPublicOrganizationsRoute:
    UnprotectedApiElectricPublicOrganizationsRoute,
}

const UnprotectedRouteWithChildren = UnprotectedRoute._addFileChildren(
  UnprotectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OrganizationalRoute: OrganizationalRouteWithChildren,
  UnprotectedRoute: UnprotectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
