/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnprotectedRouteImport } from './routes/_unprotected'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreprocessSessionOrgInitRouteImport } from './routes/preprocess/session-org-init'
import { Route as PreprocessAccountSetupRouteImport } from './routes/preprocess/account-setup'
import { Route as UnprotectedSignUpRouteImport } from './routes/_unprotected/sign-up'
import { Route as UnprotectedSignInRouteImport } from './routes/_unprotected/sign-in'
import { Route as ProtectedMainRouteImport } from './routes/_protected/main'
import { Route as ApiDeleteBucketUnprotectedIdRouteImport } from './routes/api/delete-bucket-unprotected.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ProtectedApiElectricSelfOwnedResourcesRouteImport } from './routes/_protected/api/electric/self-owned-resources'
import { Route as ProtectedApiElectricResourceRoleAssignmentRouteImport } from './routes/_protected/api/electric/resource-role-assignment'

const UnprotectedRoute = UnprotectedRouteImport.update({
  id: '/_unprotected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreprocessSessionOrgInitRoute =
  PreprocessSessionOrgInitRouteImport.update({
    id: '/preprocess/session-org-init',
    path: '/preprocess/session-org-init',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreprocessAccountSetupRoute = PreprocessAccountSetupRouteImport.update({
  id: '/preprocess/account-setup',
  path: '/preprocess/account-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UnprotectedSignUpRoute = UnprotectedSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => UnprotectedRoute,
} as any)
const UnprotectedSignInRoute = UnprotectedSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => UnprotectedRoute,
} as any)
const ProtectedMainRoute = ProtectedMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiDeleteBucketUnprotectedIdRoute =
  ApiDeleteBucketUnprotectedIdRouteImport.update({
    id: '/api/delete-bucket-unprotected/$id',
    path: '/api/delete-bucket-unprotected/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedApiElectricSelfOwnedResourcesRoute =
  ProtectedApiElectricSelfOwnedResourcesRouteImport.update({
    id: '/api/electric/self-owned-resources',
    path: '/api/electric/self-owned-resources',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedApiElectricResourceRoleAssignmentRoute =
  ProtectedApiElectricResourceRoleAssignmentRouteImport.update({
    id: '/api/electric/resource-role-assignment',
    path: '/api/electric/resource-role-assignment',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof ProtectedMainRoute
  '/sign-in': typeof UnprotectedSignInRoute
  '/sign-up': typeof UnprotectedSignUpRoute
  '/preprocess/account-setup': typeof PreprocessAccountSetupRoute
  '/preprocess/session-org-init': typeof PreprocessSessionOrgInitRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/delete-bucket-unprotected/$id': typeof ApiDeleteBucketUnprotectedIdRoute
  '/api/electric/resource-role-assignment': typeof ProtectedApiElectricResourceRoleAssignmentRoute
  '/api/electric/self-owned-resources': typeof ProtectedApiElectricSelfOwnedResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof ProtectedMainRoute
  '/sign-in': typeof UnprotectedSignInRoute
  '/sign-up': typeof UnprotectedSignUpRoute
  '/preprocess/account-setup': typeof PreprocessAccountSetupRoute
  '/preprocess/session-org-init': typeof PreprocessSessionOrgInitRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/delete-bucket-unprotected/$id': typeof ApiDeleteBucketUnprotectedIdRoute
  '/api/electric/resource-role-assignment': typeof ProtectedApiElectricResourceRoleAssignmentRoute
  '/api/electric/self-owned-resources': typeof ProtectedApiElectricSelfOwnedResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_unprotected': typeof UnprotectedRouteWithChildren
  '/_protected/main': typeof ProtectedMainRoute
  '/_unprotected/sign-in': typeof UnprotectedSignInRoute
  '/_unprotected/sign-up': typeof UnprotectedSignUpRoute
  '/preprocess/account-setup': typeof PreprocessAccountSetupRoute
  '/preprocess/session-org-init': typeof PreprocessSessionOrgInitRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/delete-bucket-unprotected/$id': typeof ApiDeleteBucketUnprotectedIdRoute
  '/_protected/api/electric/resource-role-assignment': typeof ProtectedApiElectricResourceRoleAssignmentRoute
  '/_protected/api/electric/self-owned-resources': typeof ProtectedApiElectricSelfOwnedResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/sign-in'
    | '/sign-up'
    | '/preprocess/account-setup'
    | '/preprocess/session-org-init'
    | '/api/auth/$'
    | '/api/delete-bucket-unprotected/$id'
    | '/api/electric/resource-role-assignment'
    | '/api/electric/self-owned-resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main'
    | '/sign-in'
    | '/sign-up'
    | '/preprocess/account-setup'
    | '/preprocess/session-org-init'
    | '/api/auth/$'
    | '/api/delete-bucket-unprotected/$id'
    | '/api/electric/resource-role-assignment'
    | '/api/electric/self-owned-resources'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_unprotected'
    | '/_protected/main'
    | '/_unprotected/sign-in'
    | '/_unprotected/sign-up'
    | '/preprocess/account-setup'
    | '/preprocess/session-org-init'
    | '/api/auth/$'
    | '/api/delete-bucket-unprotected/$id'
    | '/_protected/api/electric/resource-role-assignment'
    | '/_protected/api/electric/self-owned-resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  UnprotectedRoute: typeof UnprotectedRouteWithChildren
  PreprocessAccountSetupRoute: typeof PreprocessAccountSetupRoute
  PreprocessSessionOrgInitRoute: typeof PreprocessSessionOrgInitRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDeleteBucketUnprotectedIdRoute: typeof ApiDeleteBucketUnprotectedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unprotected': {
      id: '/_unprotected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnprotectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preprocess/session-org-init': {
      id: '/preprocess/session-org-init'
      path: '/preprocess/session-org-init'
      fullPath: '/preprocess/session-org-init'
      preLoaderRoute: typeof PreprocessSessionOrgInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preprocess/account-setup': {
      id: '/preprocess/account-setup'
      path: '/preprocess/account-setup'
      fullPath: '/preprocess/account-setup'
      preLoaderRoute: typeof PreprocessAccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unprotected/sign-up': {
      id: '/_unprotected/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnprotectedSignUpRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/_unprotected/sign-in': {
      id: '/_unprotected/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof UnprotectedSignInRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/_protected/main': {
      id: '/_protected/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof ProtectedMainRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/delete-bucket-unprotected/$id': {
      id: '/api/delete-bucket-unprotected/$id'
      path: '/api/delete-bucket-unprotected/$id'
      fullPath: '/api/delete-bucket-unprotected/$id'
      preLoaderRoute: typeof ApiDeleteBucketUnprotectedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/api/electric/self-owned-resources': {
      id: '/_protected/api/electric/self-owned-resources'
      path: '/api/electric/self-owned-resources'
      fullPath: '/api/electric/self-owned-resources'
      preLoaderRoute: typeof ProtectedApiElectricSelfOwnedResourcesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api/electric/resource-role-assignment': {
      id: '/_protected/api/electric/resource-role-assignment'
      path: '/api/electric/resource-role-assignment'
      fullPath: '/api/electric/resource-role-assignment'
      preLoaderRoute: typeof ProtectedApiElectricResourceRoleAssignmentRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedMainRoute: typeof ProtectedMainRoute
  ProtectedApiElectricResourceRoleAssignmentRoute: typeof ProtectedApiElectricResourceRoleAssignmentRoute
  ProtectedApiElectricSelfOwnedResourcesRoute: typeof ProtectedApiElectricSelfOwnedResourcesRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMainRoute: ProtectedMainRoute,
  ProtectedApiElectricResourceRoleAssignmentRoute:
    ProtectedApiElectricResourceRoleAssignmentRoute,
  ProtectedApiElectricSelfOwnedResourcesRoute:
    ProtectedApiElectricSelfOwnedResourcesRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface UnprotectedRouteChildren {
  UnprotectedSignInRoute: typeof UnprotectedSignInRoute
  UnprotectedSignUpRoute: typeof UnprotectedSignUpRoute
}

const UnprotectedRouteChildren: UnprotectedRouteChildren = {
  UnprotectedSignInRoute: UnprotectedSignInRoute,
  UnprotectedSignUpRoute: UnprotectedSignUpRoute,
}

const UnprotectedRouteWithChildren = UnprotectedRoute._addFileChildren(
  UnprotectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  UnprotectedRoute: UnprotectedRouteWithChildren,
  PreprocessAccountSetupRoute: PreprocessAccountSetupRoute,
  PreprocessSessionOrgInitRoute: PreprocessSessionOrgInitRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDeleteBucketUnprotectedIdRoute: ApiDeleteBucketUnprotectedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
